plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

packageExtensions:
  'cspell@*':
    dependencies:
      '@cspell/cspell-types': '*'

yarnPath: .yarn/releases/yarn-3.6.0.cjs
